services:
  - type: web
    name: feed-me-daddy-server
    env: node
    plan: free
    rootDir: server
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
